version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_graphql
    enviroment:
      - APP_NAME=Marvel
      - PORT=4000
      - DEFAULT_CURRENCY=USD
    ports:
      - '4000:4000'
    networks:
      - nestjs_graphql

networks:
  nestjs_graphql:
    driver: bridge